# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7514ff7eaba659b7502b8a4d97faacb7b4c3daad025575edc4f185af5c46dd6eeba6fc1a5402656982e0b516a5d13148073442216b441b5b544331d8bfbd701b

test:
  secret_key_base: 10967efb8e070666daeb21d5fa3df8f398d099c4da96f5b729df629261eebe17b729374dadd9a5e9595ae7869888202f6fc03cd8829027133b0509de6d54b949

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
